### ISSUE TITLE
LaZagne 2.4.3 [Linux]:  AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by linxon** [AlessandroZ/LaZagne#428]
can you help me?

lazagne-2.4.3
python-3.6.5

```bash
linxon@minako-chan /tmp/linxon-tmp-files $ lazagne browsers

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/lazagne", line 212, in <module>
    for run in runLaZagne(category, subcategories):
  File "/usr/lib/python-exec/python3.6/lazagne", line 95, in runLaZagne
    for pwd_dic in run_lazagne(category_selected=category_selected, subcategories=subcategories):
  File "/usr/lib64/python3.6/site-packages/lazagne/config/run.py", line 82, in run_lazagne
    for r in run_modules(category_selected, subcategories):
  File "/usr/lib64/python3.6/site-packages/lazagne/config/run.py", line 67, in run_modules
    for cat in OrderedDict(reversed(sorted(categories.items(), key=lambda t: t[0]))):
AttributeError: 'list' object has no attribute 'items'
```

**Comment by plonibarploni** [comment]
This only appears when running a specific module, when running 'all` it runs fine.

It is likely caused by #424. I don't have time right now to investigate further, but I'll try to get to it in the next couple of days.

**Comment by trossets** [comment]
Hi,
As I had the same issue I looked quickly at the code. I think the problem comes from the following line in file Linux/lazagne/config/run.py :
    categories = [category_selected] if category_selected != 'all' else get_categories()
When running a specific module, the variable category_selected is different from 'all' and then categories is assigned a list value but categories should be a dictionary value.
This could be fixed with the following patch:
    categories = {category_selected: get_categories()[category_selected]} if category_selected != 'all' else get_categories()
But in my case (category_selected == 'browers') I was missing also the 'wallet' category to make it work (needed to initialize constant.chrome_storage).

**Comment by plonibarploni** [comment]
@trossets Thank you for finding the cause of the issue. Changing `[category_selected]` to a dict fixes the issue.

@AlessandroZ what is the best way to fix this?

**Comment by AlessandroZ** [comment]
Thanks @trossets for your fix :+1:
